apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: nginx
    purpose: ingress
spec:
    replicas: 1
    selector:
      matchLabels:
        app: nginx
        purpose: ingress 
    template:
      metadata:
        labels:
          app: nginx
          purpose: ingress
      spec:
        containers:
        - name: app1
          image: joindevops/app1:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec: 
  selector:
    name: app1
    purpose: ingress    
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
